version: "3.8"

services:
  db:
    image: postgres:15
    container_name: cartapp_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cartdb
    volumes:
      # Aponta para a pasta de scripts dentro do backend
      - ./backend/scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: cartapp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  api:
    build:
      # O contexto do build agora é a pasta backend
      context: ./backend
      dockerfile: Dockerfile
    container_name: cartapp_backend
    restart: always
    volumes:
      # Mapeia a pasta backend local para a pasta /app no container
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=cartdb
      - DB_USER=admin
      - DB_PASSWORD=admin
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cartapp_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1

  lint:
    build:
      # O contexto do build também é a pasta backend
      context: ./backend
      dockerfile: Dockerfile
    # O comando agora roda a partir da pasta /app (que é a ./backend)
    command: bash scripts/lint.sh
    volumes:
      - ./backend:/app

volumes:
  pgdata:
